USE creParc;
ALTER TABLE Segment 
    ADD COLUMN nbSalle TINYINT(2) DEFAULT 0,
    ADD COLUMN nbPoste TINYINT(2) DEFAULT 0;

ALTER TABLE Logiciel 
    ADD COLUMN nbInstall TINYINT(2) DEFAULT 0;

ALTER TABLE Poste 
    ADD COLUMN nbLog TINYINT(2) DEFAULT 0;

SHOW TABLES;
DESCRIBE Segment;
DESCRIBE Logiciel;
DESCRIBE Poste;

ALTER TABLE Salle
    MODIFY nomSalle VARCHAR(30);
ALTER TABLE Segment
    MODIFY nomSegment VARCHAR(15);
ALTER TABLE Segment
    MODIFY nomSegment VARCHAR(14);
DESCRIBE Salle;
DESCRIBE Segment;

ALTER TABLE Poste 
ADD FOREIGN KEY (indIP) REFERENCES Segment(indIP),
ADD FOREIGN KEY (nSalle) REFERENCES Salle(nSalle),
ADD FOREIGN KEY (typePoste) REFERENCES Types(typeLP);

ALTER TABLE Installer
ADD FOREIGN KEY (nPoste) REFERENCES Poste(nPoste),
ADD FOREIGN KEY (nLog) REFERENCES Logiciel(nLog);

DELETE FROM Salle
WHERE indIP NOT IN (SELECT indIP FROM Segment);

INSERT INTO Types VALUES ('BeOS', 'Système Be');

ALTER TABLE Salle
ADD FOREIGN KEY (indIP) REFERENCES Segment(indIP);
ALTER TABLE Logiciel
ADD FOREIGN KEY (typeLog) REFERENCES Types(typeLP);